<?php

/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Vilex\VileX;
use Website\Domain\Contato\Entities\ContatoRecebido;

/** @var VileX $this */

/** @var array $lista_contatos */
$lista_contatos = $this->getAtributo('lista-contatos');
$filtro = $this->getAtributo('filtro');
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<nav class="menu-opcoes">
    <form id="filtro-registros" class="filtro-registros">
        <div class="multi-select">
            <span class="multi-select-item">Procurar em...</span>

            <div class="multi-select-itens">
                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="nome"<?php echo empty($filtro['campos']) || in_array('nome', $filtro['campos']) ? ' checked' : '' ?>>
                    Nome
                </label>

                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="email"<?php echo empty($filtro['campos']) || in_array('email', $filtro['campos']) ? ' checked' : '' ?>>
                    Email
                </label>

                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="telefone"<?php echo empty($filtro['campos']) || in_array('telefone', $filtro['campos']) ? ' checked' : '' ?>>
                    Telefone
                </label>
            </div>
        </div>

        <input type="search" name="busca" value="<?php echo $filtro['busca'] ?>" placeholder="Encontrar contatos recebidos" class="form-controle">
    </form>

    <button type="submit" form="filtro-registros" class="botao-buscar">Buscar</button>
</nav>

<table id="lista-contatos-recebidos" class="lista-registros">
    <thead>
    <tr>
        <th id="contato-recebido-id">ID</th>
        <th id="assunto">Assunto</th>
        <th id="nome">Nome</th>
        <th id="email">Email</th>
        <th id="telefone">Telefone</th>
        <th id="opcoes">Opções</th>
    </tr>
    </thead>

    <tbody>
    <?php if (!count($lista_contatos)) : ?>
        <tr>
            <td colspan="6" class="sem-registros">Nenhum contato recebido foi encontrado.</td>
        </tr>
    <?php endif;

    /** @var ContatoRecebido $contato_recebido */
    foreach ($lista_contatos as $contato_recebido) : ?>
        <tr>
            <td headers="contato-recebido-id"><?php echo $contato_recebido->getId() ?></td>
            <td headers="assunto"><?php echo $contato_recebido->getAssunto() ?: 'Não informado' ?></td>
            <td headers="nome">
                <?php echo $contato_recebido->getNome() ?>
            </td>
            <td headers="email">
                <?php echo $contato_recebido->getEmail() ?>
            </td>
            <td headers="telefone">
                <?php echo $contato_recebido->getTelefone() ?>
            </td>
            <td headers="opcoes">
                <!-- a href="/painel-dlx/contatos/detalhe?permissao_usuario_id=<?php echo $contato_recebido->getId() ?>" class="link-detalhe" title="">
                    Detalhe
                </a -->

                <a href="javascript:" class="link-excluir" onclick="excluirContatoRecebido(<?php echo $contato_recebido->getId() ?>)" title="Excluir essa permissão">
                    Excluir
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
[/CORPO]