<?php
/**
 * website-dlx
 * @version: v1.17.11
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/website-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Ajudantes\HTMLForm;
use DLX\Ajudantes\Strings;

if(!isset($params)) {
    $params = $this->obterParams();
} // Fim if
?>

[DLX-CONTEUDO]
<form id="form-<?php echo $params['html:form-id'] ?>" method="post" action="<?php echo $params['html:form-acao'] ?>" class="form-contato">
    <p class="form-paragr">
        <?php echo HTMLForm::campoGeral('texto', 'nome', 'nome', null, $this->traduzir('Nome completo', 'website-dlx'), null, [
            'maxlength' => 150,
            'required'  => 'required'
        ]) ?>
    </p>

    <p class="form-paragr">
        <?php echo HTMLForm::campoGeral('email', 'email', 'email', null, $this->traduzir('Email', 'website-dlx'), null, [
            'maxlength' => 200,
            'required'  => 'required'
        ]) ?>
    </p>

    <p class="form-paragr">
        <?php echo HTMLForm::campoTelefone('telefone', 'telefone', null, $this->traduzir('Telefone', 'website-dlx')) ?>
    </p>

    <?php if (count($params['lista:assuntos']) > 0) : ?>
        <p class="form-paragr">
            <?php echo HTMLForm::comboSelect('assunto', 'assunto', null, $this->traduzir('Assunto', 'website-dlx'), null, [
                'required' => 'required'
            ], $params['lista:assuntos']) ?>
        </p>
    <?php endif ?>

    <p class="form-paragr">
        <?php echo HTMLForm::caixaTexto('mensagem', 'mensagem', null, $this->traduzir('Mensagem', 'webstie-dlx'), null, [
            'required' => 'required'
        ]) ?>
    </p>

    <div class="form-botoes">
        <?php echo HTMLForm::botao('salvar', $this->traduzir('Enviar', 'painel-dlx')) ?>
    </div>
</form>
[/DLX-CONTEUDO]
