<?php

/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Vilex\VileX;
use Website\Domain\FormContato\Entities\AssuntoContato;

/** @var VileX $this */

/** @var array $lista_assuntos */
$lista_assuntos = $this->getAtributo('lista-assuntos');
?>

[CORPO]
<form id="form-contato" method="post" action="/form-contato/enviar">
    <p class="form-paragr">
        <label for="txt-nome" class="form-rotulo">Nome:</label>
        <input type="text" name="nome" id="txt-nome" required>
    </p>

    <p class="form-paragr">
        <label for="txt-email" class="form-rotulo">Email:</label>
        <input type="email" name="email" id="txt-email" required>
    </p>

    <p class="form-paragr">
        <label for="txt-telefone" class="form-rotulo">Telefone:</label>
        <input type="tel" name="telefone" id="txt-telefone">
    </p>

    <?php if (count($lista_assuntos) > 0) : ?>
        <p class="form-paragr">
            <label for="sel-assunto" class="form-rotulo">Assunto:</label>
            <select name="assunto" id="sel-assunto" required>
                <option value="">Selecione um assunto</option>

                <?php
                /** @var AssuntoContato $assunto */
                foreach ($lista_assuntos as $assunto) : ?>
                <option value="<?php echo $assunto->getId() ?>">
                    <?php echo $assunto->getDescricao() ?>
                </option>
                <?php endforeach; ?>
            </select>
        </p>
    <?php endif; ?>

    <p class="form-paragr">
        <label for="txt-mensagem" class="form-rotulo">Mensagem:</label><br>
        <textarea name="mensagem" id="txt-mensagem" required></textarea>
    </p>

    <p class="form-botoes">
        <button type="submit" class="botao">Enviar</button>
    </p>
</form>
[/CORPO]

[SCRIPTS]
<script>
    $('#form-contato').formAjax({
        func_depois: function (json, status, xhr) {
            alert(json.mensagem);
            window.location.reload();
        }
    });

    $('#txt-telefone').mascara('(00) 0 0000-0000');
</script>
[/SCRIPTS]