<?php
/**
 * website-dlx
 * @version: v1.17.11
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-11-23. Please report any bug at
 * https://github.com/dlepera88-php/website-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
use DLX\Ajudantes\HTMLForm;

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

define('HTML_MENU_LINK', '<a href="%s" class="link">%s</a>')
?>

[DLX-MENU]
<?php if (count($params['html:itens-menu']) > 0) : ?>
    <ul class="menu-principal">
        <?php foreach ($params['html:itens-menu'] as $item_menu) : ?>
            <li class="item">
                <?php printf(HTML_MENU_LINK, $item_menu['LINK'], $item_menu['TEXTO']);

                if (array_key_exists('SUBMENU', $item_menu)) : ?>
                    <ul class="sub-menu">
                        <?php foreach ($item_menu['SUBMENU'] as $item_submenu) : ?>
                            <li class="item">
                                <?php
                                    printf(HTML_MENU_LINK, $item_submenu['LINK'], $item_submenu['TEXTO']);
                                    printf('<span class="descr">%s</span>', $item_submenu['DESCR'])
                                ?>
                            </li>
                        <?php endforeach ?>
                    </ul>
                <?php endif ?>
            </li>
        <?php endforeach ?>
    </ul>
<?php endif ?>
[/DLX-MENU]
