<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Core\Configure;
use PainelDLX\Domain\Usuarios\Entities\Usuario;
use SechianeX\Factories\SessionFactory;
use Vilex\PaginaMestra;
use Vilex\VileX;

?>

<html lang="pt">
<head>
    <base href="<?php echo Configure::get('app', 'base-html') ?>">
    <meta name="Content-type" content="text-html">
    <meta name="charset" content="UTF-8">
    <link rel="shortcut icon" type="image/png" href="<?php echo Configure::get('app', 'favicon') ?>">

    <!-- Tamanho do dispositivo -->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <title><?php echo Configure::get('app', 'nome-amigavel') ?></title>

    [ARQUIVOS-CSS/]
    [HTML-HEAD/]
</head>

<body>

<nav class="dlx-menu">
    <a href="/" class="logo-site">
        <?php echo Configure::get('app', 'nome-amigavel') ?>
    </a>

    <div class="menu-principal">
        <div class="menu-item">
            <a href="/contato" class="menu-link">Contato</a>
        </div>
    </div>
</nav>

<div class="wrapper">
    <header class="dlx-topo">
        [TOPO/]
    </header>

    <div class="dlx-conteudo">
        [MENSAGEM-USUARIO/]
        [CORPO/]
    </div>

    <footer class="dlx-rodape">
        [RODAPE/]
    </footer>
</div>

<div id="status-ajax"></div>

<script src="/vendor/components/jquery/jquery.min.js"></script>
[ARQUIVOS-JAVASCRIPT/]
[SCRIPTS/]
</body>
</html>
