<?php
/**
 * aplicativo
 * @version: versão
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/framework-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Ajudantes\HTMLForm;
use DLX\Ajudantes\Strings;

if(!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$config = $params['modelo'];
?>

[DLX-CONTEUDO]
<form id="form-<?php echo $params['html:form-id'] ?>" method="post" action="<?php echo $params['html:form-acao'] ?>" data-url-detalhes="<?php echo $params['conf:form-url-lista'] ?>" data-url-editar="<?php echo $params['conf:form-url-editar'] ?>">
    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Geral', 'painel-dlx') ?></legend>

        <p class="form-paragr">
            <?php echo HTMLForm::comboSelect('tema', 'tema', $config->getTema(), $this->traduzir('Tema'), null, [
                'required' => 'required'
            ], $params['lista:temas']); ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('email', 'email_contato', 'email-contato', $config->getEmailContato(), $this->traduzir('Email para contato', 'website-dlx'), $this->traduzir('Email que receberá qualquer contato realizado através do site caso nenhum outro seja informado no momento do envio. Caso fique em branco, pode ser que nenhum email seja enviado.', 'website-dlx'), [
                'maxlength' => 200
            ]) ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Google Analytics', 'painel-dlx') ?></legend>
        
        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'ga_ua', 'ga-ua', $config->getGaUa(), $this->traduzir('ID de acompanhamento', 'painel-dlx'), null, [
                'data-mask' => 'UA-0000000-00'
            ]) ?>
        </p>
    </fieldset>
 
    <div class="form-botoes">
        <?php echo HTMLForm::botao('salvar', $this->traduzir('Salvar', 'painel-dlx')),
            HTMLForm::botao('cancelar', $this->traduzir('Cancelar', 'painel-dlx')) ?>
    </div>
</form>
[/DLX-CONTEUDO]
