<?php
/**
 * aplicativo
 * @version: versão
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/framework-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Ajudantes\HTMLForm;

if(!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$info_contato = $params['modelo'];
$tipo_info = $params['modelo:tipo-info'];
?>

[DLX-CONTEUDO]
<form id="form-<?php echo $params['html:form-id'] ?>" method="post" action="<?php echo $params['html:form-acao'] ?>" data-url-lista="<?php echo $params['conf:form-url-lista'] ?>" data-url-novo="<?php echo $params['conf:form-url-novo'] ?>" data-url-editar="<?php echo $params['conf:form-url-editar'] ?>" data-url-lista="<?php echo $params['conf:form-url-lista'] ?>" data-url-novo="<?php echo $params['conf:form-url-novo'] ?>" data-url-editar="<?php echo $params['conf:form-url-editar'] ?>">
    <?php echo HTMLForm::array2Input($params['lista:pk-tabela']) ?>
    
    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Geral', 'painel-dlx') ?></legend>

        <p class="form-paragr">
            <label for="sel-tipo" class="form-rotulo"><?php echo $this->traduzir('Tipo', 'website-dlx') ?>:</label>
            <select name="tipo" id="sel-tipo" class="form-controle -select" required>
                <option value=""><?php echo $this->traduzir('Selecione uma opção') ?></option>
                <?php foreach ($params['lista:tipos-infos'] as $rede_social => $options) :
                    $grupo_opt = $rede_social === 1 ? $this->traduzir('Redes Sociais', 'website-dlx') : $this->traduzir('Informações de contato', 'website'); ?>
                    <optgroup label="<?php echo $grupo_opt ?>">
                        <?php echo implode("\n", array_map(function ($o) use ($info_contato) {
                            return sprintf('<option value="%s"%s>%s</option>', $o['tipo_info_id'], $o['tipo_info_id'] == $info_contato->getTipo() ? ' SELECTED' : '', $o['tipo_info_nome']);
                        }, $options)); ?>
                    </optgroup>
                <?php endforeach ?>
            </select>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'valor', 'valor', $info_contato->getValor(), $this->traduzir('Informação de contato', 'website-dlx'), null, [
                'maxlength' => 255,
                'pattern' => $tipo_info->getValidacao(),
                'data-mask' => $tipo_info->getMask(),
                'data-prefixo' => $tipo_info->getPrefixo(),
                'required'  => 'required'
            ]) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'exibicao', 'exibicao', $info_contato->getExibicao(), $this->traduzir('Exibição', 'website-dlx'), $this->traduzir('Obs: Ao alterar o campo <b>Valor</b>, esse será alterado automaticamente.', 'website-dlx'), [
                'maxlength' => 255,
                'required'  => 'required'
            ]) ?>
        </p>
    </fieldset>

    <p class="form-paragr">
        <?php echo HTMLForm::chkSimNao('publicar', 'publicar', $info_contato->isPublicar(), $this->traduzir('Ativar?', 'painel-dlx')); ?>
    </p>

    <div class="form-botoes">
        <?php echo HTMLForm::botao('salvar', $this->traduzir('Salvar', 'painel-dlx')),
            HTMLForm::botao('cancelar', $this->traduzir('Cancelar', 'painel-dlx')) ?>
    </div>
</form>
[/DLX-CONTEUDO]

[DLX-SCRIPTS]
<script>
    $('#sel-tipo').on('change.__script', function () {
        $.get('website/tipos-de-informacoes/obter-configuracoes', 'tipo=' + $(this).val(), function (config) {
            if (config !== false) {
                var $valor = $('#txt-valor');
                
                if (config.mascara == '') {
                    $valor.removeAttr('data-mask');

                    // Remover a máscara no campo
                    $valor.removerMascara();
                } else {
                    $valor.attr('data-mask', config.mascara);

                    // Reaplicar a máscara no campo
                    $valor.mascara(config.mascara);
                } // Fim if ... else

                config.validacao == '' ? $valor.removeAttr('pattern') : $valor.attr('pattern', config.validacao);
                config.prefixo == '' ? $valor.removeAttr('data-prefixo') : $valor.attr('data-prefixo', config.prefixo);
            } // Fim if
        }, 'json');
    });

    $('#txt-valor').on('change.__script', function () {
        $('#txt-exibicao').val($(this).val());
    });
</script>
[/DLX-SCRIPTS]
