<?php
/**
 * aplicativo
 * @version: versão
 * @author: Diego Lepera
 *
 * Created by Diego Lepera on 2017-07-28. Please report any bug at
 * https://github.com/dlepera88-php/framework-dlx/issues
 *
 * The MIT License (MIT)
 * Copyright (c) 2017 Diego Lepera http://diegolepera.xyz/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Ajudantes\HTMLForm;

if(!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$tipo_info = $params['modelo'];
?>

[DLX-CONTEUDO]
<form id="form-<?php echo $params['html:form-id'] ?>" method="post" action="<?php echo $params['html:form-acao'] ?>" data-url-lista="<?php echo $params['conf:form-url-lista'] ?>" data-url-novo="<?php echo $params['conf:form-url-novo'] ?>" data-url-editar="<?php echo $params['conf:form-url-editar'] ?>" data-url-lista="<?php echo $params['conf:form-url-lista'] ?>" data-url-novo="<?php echo $params['conf:form-url-novo'] ?>" data-url-editar="<?php echo $params['conf:form-url-editar'] ?>">
    <?php echo HTMLForm::array2Input($params['lista:pk-tabela']) ?>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo $this->traduzir('Geral', 'painel-dlx') ?></legend>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'nome', 'nome', $tipo_info->getNome(), $this->traduzir('Nome', 'website-dlx'), null, [
                'maxlength' => 100,
                'required'  => 'required'
            ]) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::chkSimNao('rede_social', 'rede-social', $tipo_info->isRedeSocial(), $this->traduzir('É uma rede social?', 'website-dlx')); ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <lengend class="form-legenda"><?php echo $this->traduzir('Configurações', 'painel-dlx') ?></lengend>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'prefixo', 'prefixo', $tipo_info->getPrefixo(), $this->traduzir('Prefixo', 'website-dlx'), $this->traduzir('Prefixo da informação de contato. Não será necessário que seja digitada ao adicionar ou editar uma informação de contato.', 'website-dlx'), [
                'maxlength' => 100
            ]) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'validacao', 'validacao', $tipo_info->getValidacao(), $this->traduzir('Validação', 'website-dlx'), $this->traduzir('Expressão regular para validar a informação que está sendo incluída.', 'website-dlx'), [
                'maxlength' => 100
            ]) ?>
        </p>

        <p class="form-paragr">
            <?php echo HTMLForm::campoGeral('texto', 'mask', 'mask', $tipo_info->getMask(), $this->traduzir('Máscara', 'website-dlx'), $this->traduzir('Máscara a ser aplicada a informação de contato.', 'website-dlx'), [
                'maxlength' => 100
            ]) ?>
        </p>
    </fieldset>

    <p class="form-paragr">
        <?php echo HTMLForm::chkSimNao('publicar', 'publicar', $tipo_info->isPublicar(), $this->traduzir('Ativar?', 'painel-dlx')); ?>
    </p>

    <div class="form-botoes">
        <?php echo HTMLForm::botao('salvar', $this->traduzir('Salvar', 'painel-dlx')),
            HTMLForm::botao('cancelar', $this->traduzir('Cancelar', 'painel-dlx')) ?>
    </div>
</form>
[/DLX-CONTEUDO]
